### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by felix021** [parkomat/parkomat#1]
after set $GOPATH to ~/gocode and run the go get command, it reported error, as shown below:

> $ go get github.com/parkomat/parkomat
> \# github.com/miekg/dns
> gocode/src/github.com/miekg/dns/client.go:431: undefined: tls.DialWithDialer
> gocode/src/github.com/miekg/dns/dnssec.go:257: undefined: crypto.Signer
> gocode/src/github.com/miekg/dns/dnssec.go:321: undefined: crypto.Signer
> gocode/src/github.com/miekg/dns/sig0.go:16: undefined: crypto.Signer
> \# golang.org/x/net/webdav
> gocode/src/golang.org/x/net/webdav/webdav.go:619: (&url.URL literal).EscapedPath undefined (type *url.URL has no field or method EscapedPath)

**Comment by zgli1980** [comment]
same here.......ace

go get github.com/parkomat/parkomat
# golang.org/x/net/webdav
go/src/golang.org/x/net/webdav/webdav.go:619: (&url.URL literal).EscapedPath undefined (type *url.URL has no field or method EscapedPath)

**Comment by elcct** [comment]
Which version of Go are you using? 

I am not able to reproduce it...

**Comment by elcct** [comment]
Ok it seems like the problem occurs with Go 1.4.

I suggest using at least Go 1.5

**Comment by felix021** [comment]
thanks, my Ubuntu 14.04 distributes with go version go1.2...

**Comment by elcct** [comment]
@felix021 please check this project https://github.com/moovweb/gvm

It works well with Ubuntu 14.04 and makes you use latest Go versions easily.
